# Generated by Django 4.2.4 on 2023-08-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_comment_delete_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='kamau', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=94343, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='phone_to_call',
            field=models.CharField(default=943904, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='reward',
            field=models.CharField(default=200, max_length=250),
            preserve_default=False,
        ),
    ]
